galaxy_info:
  author: Hispanico
  description: Manage Nginx as Reverse Proxy
  license: GPLv3

  min_ansible_version: 2.4

  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - xenial

  galaxy_tags:
  - system
  - nginx
  - reverse proxy

dependencies: []
